### PR TITLE
Fix/899 grid item min width

### LINKED ISSUE #899: [Bug?]: Grid items overflowing when child uses nowrap and text-overflow
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When a grid item's content pushes the width beyond the grid, it overflows.

### Expected behavior 🤔

Grid item should constrain the widths of its children.

This can be fixed by adding `min-width: 0` to the grid items

### Steps to reproduce 🕹

Steps:

1. Create a grid and add grid items spanning the full width
2. Add a child to one of the grid items using `white-space: nowrap` and overflow, text-overflow
3.
4.

Can also visit https://pluralsight.github.io/a11y-test-app and remove the min-width from the right-most sidebar to observe.

### Context 🔦

_No response_

### Your environment 🌎

_No response_

### PR DESCRIPTION
**Pull request by Rykus0**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

closes #899 

## What is the new behavior?

Adds `min-width: 0` to grid item

### CODE REVIEW

File: packages/headless-styles/src/components/Grid/gridJS.ts [hunk 1]
```diff
@@ -24,8 +24,12 @@ export function getJSGridProps(options?: GridOptions) {
 export function getJSGridItemProps(options?: GridItemOptions) {
   const defaultOptions = getDefaultGridItemOptions(options)
   const { style } = createGridItemProps(defaultOptions)
+  const itemStyles = {
```
Comment (caseybaggz) [inline packages/headless-styles/src/components/Grid/gridJS.ts:27]: Not seeing a reason to create this var. Let's just put it as the param.

Comment (Rykus0) [reply packages/headless-styles/src/components/Grid/gridJS.ts:27]: Sure thing.  I only did it to be consistent with the grid container function.
